// vibe-react/src/App.js
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';

import Store from './store/Store';
import Todo from './store/models/Todo';
import Vibe from 'vibejs'

const types = Vibe.types;

const struct = new Vibe.Struct(
  {
    structure: {
      todos: types.Array(types.Reference(Todo.name)),
      undoneFirst: types.Boolean
    },
    computed: {
      doneTodos() {
        return this.todos.filter(it => it.done);
      },
      undoneTodos() {
        return this.todos.filter(it => !it.done);
      }
    }
  },
  Store
).observe();

const vibeReact = (component, structure) => {
  return class extends Component{ 
    
    structure = structure

    constructor(){
      super();
      this.state = {
        structure: this.structure.$json()
      }
      this.structure.$observable.subscribe(_ => {
        this.setState({
          structure: this.structure.$json()
        })
      })
    }

    render(){
      return React.createElement(component, {
          structure: this.state.structure
      })
    }
  }
}


class App extends Component {

  state = {
    todoTitle: "",
    todoDescription: ""
  }

  addNewTodo(){
    const entity = {
      id: new Date().getTime(),
      title: this.state.todoTitle,
      description: this.state.todoDescription,
      done: false
    };
    console.log(entity);
    Todo.insertEntity(entity);
    struct.todos = struct.todos.concat([entity.id]);
    
  }

  render() {
    return (
      <div className="App">
        <h1>Welcome to the vibe + react example!</h1>
        <table style={{width: '100%'}}>
          <tr style={{border: '1px solid black', borderCollapse: 'collapse' }}>
            <th style={{border: '1px solid black', borderCollapse: 'collapse' }} >Title</th>
            <th style={{border: '1px solid black', borderCollapse: 'collapse' }}>Description</th> 
            <th style={{border: '1px solid black', borderCollapse: 'collapse' }}>Done</th>
          </tr>
          {
            struct.todos.map(todo => {
              return (
                <tr style={{border: '1px solid black', borderCollapse: 'collapse' }} >
                  <th style={{border: '1px solid black', borderCollapse: 'collapse' }}>{ todo.title + ' ' + todo.done }</th>
                  <th style={{border: '1px solid black', borderCollapse: 'collapse' }}>{todo.description}</th> 
                  <th style={{border: '1px solid black', borderCollapse: 'collapse' }}>
                    <input type="checkbox" onChange={ e => todo.done = e.target.value} />
                  </th>
                </tr>
              )
            })
          }
        </table>

        <form onSubmit={this.addNewTodo.bind(this)} style={{ padding: '10px',  display: 'flex', flexDirection: 'column'}} action="#">
          <input type="text" placeholder="New todo's name" onChange={text => this.setState({todoTitle: text.target.value})} />
          <textarea name="" id="" cols="10" rows="10" placeholder="Description" onChange={text => this.setState({todoDescription: text.target.value})}></textarea>
          <input type="submit" value="Add todo" />
        </form>
      </div>
    );
  }
}

export default vibeReact(App, struct);

// vibe-vue/src/App.vue
<template>
  <div id="app">
    <div class="todo-list">
      <input id="undoneFirst" type="checkbox" v-model="component.undoneFirst">
      <label for="undoneFirst">Show undone todos first</label>
      <table>
          <tr>
            <th>Title</th>
            <th>Description</th> 
            <th>Done</th>
          </tr>
          <template v-if="component.undoneFirst">
            <tr v-for="todo in component.undoneTodos" :key="todo.id">
              <th>{{todo.title}}}</th>
              <th>{{todo.description}}</th> 
              <th><input type="checkbox" v-model="todo.done"></th>
            </tr>
            <tr v-for="todo in component.doneTodos" :key="todo.id">
              <th>{{todo.title}}}</th>
              <th>{{todo.description}}</th> 
              <th><input type="checkbox" v-model="todo.done"></th>
            </tr>

          </template>
          <template v-else >
            <tr v-for="todo in component.doneTodos" :key="todo.id">
              <th>{{todo.title}}}</th>
              <th>{{todo.description}}</th> 
              <th><input type="checkbox" v-model="todo.done"></th>
            </tr>
            <tr v-for="todo in component.undoneTodos" :key="todo.id">
              <th>{{todo.title}}}</th>
              <th>{{todo.description}}</th> 
              <th><input type="checkbox" v-model="todo.done"></th>
            </tr>
          </template>
          
      </table>
    </div>

    <form class="new-todo" action="#">
      <input type="text" placeholder="New todo's name" v-model="newTodoTitle" />
      <textarea name="" id="" cols="10" rows="10" placeholder="Description" v-model="newTodoDescription"></textarea>
      <button @click="createNewTodo">New Todo</button>
    </form>
  </div>
</template>

<script>
import HelloWorld from "./components/HelloWorld";
import Vibe from "vibejs";
import Todo from "../src/store/models/Todo";
import Store from "../src/store/Store";

const types = Vibe.types;

const struct = new Vibe.Struct(
  {
    structure: {
      todos: types.Array(types.Reference(Todo.name)),
      undoneFirst: types.Boolean
    },
    computed: {
      doneTodos() {
        return this.todos.filter(it => it.done);
      },
      undoneTodos() {
        return this.todos.filter(it => !it.done);
      }
    }
  },
  Store
);

export default {
  name: "app",
  data() {
    return {
      component: struct.observe(),
      newTodoTitle: "",
      newTodoDescription: ""
    };
  },
  mounted() {
    this.component.$observable.subscribe(_ => {
      this.$forceUpdate();
    });
  },
  methods: {
    createNewTodo() {
      const entity = {
        id: new Date().getTime(),
        title: this.newTodoTitle,
        description: this.newTodoDescription,
        done: false
      };
      Todo.insertEntity(entity);
      this.component.todos = this.component.todos.concat([entity.id]);

      console.log(this.component.todos);
      this.newTodoDescription = "";
      this.newTodoTitle = "";
    },
    changeUserName(user, name) {
      user.name = name;
    }
  },
  components: {}
};
</script>

<style>
.todo-item {
  display: flex;
  flex-direction: column;
  margin-top: 10px;
}

.todo-item-editor {
  display: flex;
  flex-direction: row;
  margin-top: 10px;
}
.todo-list {
  padding: 10px;
}

#app {
  width: 500px;
  margin: auto;
  margin-top: 100px;
}

.new-todo {
  padding: 10px;
  display: flex;
  flex-direction: column;
}

table {
  width: 100%;
}
table,
th,
td {
  border: 1px solid black;
  border-collapse: collapse;
}
th,
td {
  padding: 5px;
  text-align: left;
}
</style>
